SET @stmt = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='task_instance' AND COLUMN_NAME='analysis_json') = 0,
  'ALTER TABLE task_instance ADD COLUMN analysis_json TEXT NOT NULL',
  'SELECT 1'
));
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;
