SET @stmt = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='task' AND COLUMN_NAME='image') = 0,
  'ALTER TABLE task ADD COLUMN image VARCHAR(512) NOT NULL DEFAULT ''''',
  'SELECT 1'
));
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;
