package model

import "time"

// TaskInstance captures one concrete execution attempt generated by the scheduler.
type TaskInstance struct {
	ID                 int64
	TaskID             int64
	ScheduleInstanceID string
	ShardNo            int    // shard index (0-based, 0 for non-sharded)
	ShardTotal         int    // total shard count (0 for non-sharded)
	TriggerTime        time.Time
	DispatchTime       time.Time
	StartedAt          time.Time
	FinishedAt         time.Time
	WorkerID           string
	Status             string
	RetryCount         int
	ErrorCode          string
	ErrorMessage       string
	AnalysisJSON       string    // AI analysis result for failed instances
	NextRetryTime      time.Time
	TraceID            string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

