package model

import "time"

// TaskInstance captures one concrete execution attempt generated by the scheduler.
type TaskInstance struct {
	ID                 int64
	TaskID             int64
	ScheduleInstanceID string
	TriggerTime        time.Time
	DispatchTime       time.Time
	WorkerID           string
	Status             string
	RetryCount         int
	ErrorCode          string
	ErrorMessage       string
	TraceID            string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

