version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: go-ai-scheduler-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_ai_scheduler
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: go-ai-scheduler-redis
    ports:
      - "6379:6379"

  etcd:
    image: quay.io/coreos/etcd:v3.5.14
    container_name: go-ai-scheduler-etcd
    environment:
      ETCD_NAME: node1
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER: node1=http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: go-ai-scheduler-cluster
    ports:
      - "2379:2379"
      - "2380:2380"

volumes:
  mysql-data:
